export {
  parseCapabilitiesReport,
  parseCoreCapabilities,
  parseCoreReportAccepted,
  parseEnrollmentCreated,
  parseEnrollmentRequest,
  parseEnrollmentStatus,
  parseSyncSnapshot,
} from "./core.ts";
export type {
  CapabilitiesReport,
  CoreCapabilities,
  CorePlatform,
  CoreReportAccepted,
  CredentialSource,
  EnrollmentCreated,
  EnrollmentRequest,
  EnrollmentStatus,
  ProviderCapability,
  SyncSnapshot,
} from "./core.ts";
export { parseSyncErrorResponse, SYNC_ERROR_CODES } from "./errors.ts";
export type { SyncErrorCode, SyncErrorResponse } from "./errors.ts";
export {
  parseAdministratorAuthenticated,
  parseAdministratorLoginRequest,
  parseAdministratorSetupRequest,
  parseAdministratorStatus,
  parseBackupMetadata,
  parseConnectedCoreList,
  parseCredentialStatus,
  parseCredentialStatusList,
  parseEnrollmentDecisionRequest,
  parseModelCatalog,
  parsePendingEnrollmentList,
  parsePutCredentialRequest,
  parseRollbackSettingsRequest,
  parseServerOverview,
  parseSettingsHistory,
  parseSharedSettings,
  parseSharedSettingsView,
  parseUpdateSharedSettingsRequest,
} from "./management.ts";
export type {
  AdministratorAuthenticated,
  AdministratorLoginRequest,
  AdministratorSetupRequest,
  AdministratorStatus,
  BackupMetadata,
  ConnectedCore,
  ConnectedCoreList,
  CredentialStatus,
  CredentialStatusList,
  EnrollmentDecisionRequest,
  ModelCandidate,
  ModelCatalog,
  PendingEnrollment,
  PendingEnrollmentList,
  PutCredentialRequest,
  RollbackSettingsRequest,
  ServerOverview,
  SettingsHistory,
  SettingsHistoryEntry,
  SharedSettings,
  SharedSettingsView,
  UpdateSharedSettingsRequest,
} from "./management.ts";
export { SyncSchemaError } from "./schemas.ts";
export type { ModelRef, Parser } from "./schemas.ts";

export const SYNC_ROUTES = {
  health: "/health",
  management: {
    authStatus: "/api/management/auth/status",
    setup: "/api/management/auth/setup",
    login: "/api/management/auth/login",
    logout: "/api/management/auth/logout",
    settings: "/api/management/settings",
    overview: "/api/management/overview",
    credentials: "/api/management/credentials",
    cores: "/api/management/cores",
    enrollments: "/api/management/enrollments",
    models: "/api/management/models",
    history: "/api/management/history",
    rollback: "/api/management/history/rollback",
    backupMetadata: "/api/management/backup/metadata",
  },
  core: {
    enrollments: "/api/core/enrollments",
    snapshot: "/api/core/snapshot",
    capabilities: "/api/core/capabilities",
  },
} as const;
